apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fiapx-service.name" . }}
  labels:
    {{- include "fiapx-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . | quote }}
  {{- end }}
